import { describe, expect, it } from 'vitest';
import { brandByKey } from '@newsroom/brands';
import { accentSets, chooseArchetype, compose, isLayoutShippable, NoArchetypeError, loadPassing, TYPOGRAPHY_ONLY } from '@newsroom/design';
import { loadAllFixtures, loadFixture } from '@newsroom/render';
import { validateQuote } from '@newsroom/llm';

const brand = brandByKey('f1');

describe('the combinatorial system', () => {
  it('offers 22 valid accent sets: none, each of six, and every pair', () => {
    const sets = accentSets();
    expect(sets).toHaveLength(22);
    expect(sets.every((s) => s.length <= 2)).toBe(true);
    expect(new Set(sets.map((s) => [...s].sort().join('+'))).size).toBe(22);
  });

  it('declares 7 archetypes with exactly 4 layouts each — 28 designed layouts', () => {
    expect(brand.archetypes).toHaveLength(7);
    for (const a of brand.archetypes) expect(a.layouts).toHaveLength(4);
    expect(brand.archetypes.reduce((n, a) => n + a.layouts.length, 0)).toBe(28);
  });

  it('reaches 3,080 compositions per brand from 28 designed files', () => {
    expect(28 * 5 * 22).toBe(3080);
  });
});

describe('archetype selection comes from the data, not from taste', () => {
  it('maps every claimType the brand declares a field contract for', () => {
    for (const claimType of Object.keys(brand.requiredFields)) {
      expect(() => chooseArchetype(brand, claimType)).not.toThrow();
    }
  });

  it('refuses to guess for an unknown claimType', () => {
    expect(() => chooseArchetype(brand, 'nonsense')).toThrow(NoArchetypeError);
  });
});

describe('fixture gating — enforced in code, not by discipline', () => {
  it('has a manifest generated by the golden run', () => {
    const manifest = loadPassing();
    expect(manifest, 'run: pnpm golden').not.toBeNull();
    expect(manifest!.fixtures.length).toBeGreaterThanOrEqual(10);
  });

  it('refuses a layout that is not in the manifest for that archetype', () => {
    const manifest = loadPassing()!;
    expect(isLayoutShippable('f1', 'classification', 'hero-left', manifest)).toBe(false);
    expect(isLayoutShippable('f1', 'classification', 'stacked', manifest)).toBe(true);
  });
});

describe('compose', () => {
  const fixture = loadFixture('classification-basic');

  it('picks a contrast-safe, shippable composition for a real claim', () => {
    const spec = compose({ brand, claim: fixture.claim, history: [], hasImage: true });
    expect(spec.archetype.key).toBe('classification');
    expect(spec.archetype.layouts).toContain(spec.layout);
    expect(spec.accents.length).toBeLessThanOrEqual(2);
  });

  it('falls back to a typography-only layout when there is no image', () => {
    const spec = compose({ brand, claim: fixture.claim, history: [], hasImage: false });
    expect(TYPOGRAPHY_ONLY).toContain(spec.layout);
  });

  it('avoids the layout used by the previous post', () => {
    const first = compose({ brand, claim: fixture.claim, history: [], hasImage: true });
    const second = compose({
      brand, claim: fixture.claim, hasImage: true,
      history: [{ layout: first.layout, skin: first.skin.key, accents: [...first.accents] }],
    });
    expect(second.layout).not.toBe(first.layout);
  });

  it('is deterministic for the same claim and history', () => {
    const a = compose({ brand, claim: fixture.claim, history: [], hasImage: true });
    const b = compose({ brand, claim: fixture.claim, history: [], hasImage: true });
    expect([b.layout, b.skin.key, b.accents]).toEqual([a.layout, a.skin.key, a.accents]);
  });

  it('changes the composition when reshuffled', () => {
    const a = compose({ brand, claim: fixture.claim, history: [], hasImage: true });
    const variants = Array.from({ length: 6 }, (_, i) =>
      compose({ brand, claim: fixture.claim, history: [], hasImage: true, reshuffle: i + 1 }));
    expect(variants.some((v) => v.layout !== a.layout || v.skin.key !== a.skin.key || v.accents.join() !== a.accents.join())).toBe(true);
  });

  it('never selects a near-white entity colour onto a skin that cannot carry it', () => {
    const clash = loadFixture('colour-clash');
    const spec = compose({ brand, claim: clash.claim, history: [], hasImage: true });
    expect(spec.skin.key).toBeTruthy(); // composing at all means every pair passed assertContrast
  });

  it('composes every committed fixture without throwing', () => {
    for (const f of loadAllFixtures()) {
      expect(() => compose({ brand, claim: f.claim, history: [], hasImage: Boolean(f.imagePath) }), f.name).not.toThrow();
    }
  });
});

describe('the extraction quote contract is validated in code, not trusted', () => {
  const body = 'Norris was given a 5 second time penalty for an unsafe release in the pit lane.';

  it('accepts a quote that literally contains every number', () => {
    expect(validateQuote('Norris was given a 5 second time penalty', { penalty: 5 }, body)).toBeNull();
  });

  it('rejects a quote that does not contain the number, and says how many were covered', () => {
    // Verbatim, but it carries neither number the model put in values.
    const v = validateQuote('for an unsafe release in the pit lane.', { penalty: 5, grid: 3 }, body);
    expect(v).toBe('support found for 0 of 2 numbers');
  });

  it('rejects a quote the model invented rather than copied from the source', () => {
    expect(validateQuote('Norris said he was furious about the 5 second penalty', { penalty: 5 }, body))
      .toBe('quote not found verbatim in the source text');
  });

  it('requires no quote at all when there are no numeric values', () => {
    expect(validateQuote(null, { driver: 'Norris' }, body)).toBeNull();
  });

  it('rejects a missing quote when numbers are present', () => {
    expect(validateQuote(null, { penalty: 5 }, body)).toBe('support found for 0 of 1 numbers');
  });
});
