import type { Ctx } from './context.ts';
import { prepareReview } from './review.ts';
import { REVIEW_TTL_MINUTES } from './stages/gate.ts';
import { renderPostDesign } from './post-design.ts';

/** Owner-requested manual re-review, not an ingestion/dedupe reset or approval. */
export async function regenerateRecentF1Reviews(ctx: Ctx, limit = 12) {
  const now = ctx.now();
  const cutoff = now.getTime() - 24 * 60 * 60 * 1000;
  ctx.store.expireStaleReviews(now);
  const candidates = ctx.store.claims.filter((claim) => {
    if (claim.vertical !== 'f1' || claim.claimType === 'demo' || claim.observedAt.getTime() < cutoff || claim.observedAt > now) return false;
    const decisions = ctx.store.decisions.filter((d) => d.claimId === claim.id).sort((a, b) => b.decidedAt.getTime() - a.decidedAt.getTime());
    if (decisions[0]?.outcome !== 'review') return false;
    const reviews = ctx.store.reviews.filter((r) => r.claimId === claim.id);
    if (reviews.some((r) => ['pending', 'held', 'approved', 'rejected'].includes(r.state))) return false;
    const compositions = new Set(ctx.store.compositions.filter((c) => c.claimId === claim.id).map((c) => c.id));
    return !ctx.store.posts.some((p) => compositions.has(p.compositionId) && !['cancelled', 'failed'].includes(p.status));
  }).sort((a, b) => b.observedAt.getTime() - a.observedAt.getTime()).slice(0, Math.max(1, Math.min(24, limit)));

  const reviewIds: string[] = [];
  const errors: { claimId: string; error: string }[] = [];
  for (const claim of candidates) {
    const previous = ctx.store.reviews.filter((r) => r.claimId === claim.id).sort((a, b) => b.createdAt.getTime() - a.createdAt.getTime())[0];
    const decision = ctx.store.decisions.filter((d) => d.claimId === claim.id).sort((a, b) => b.decidedAt.getTime() - a.decidedAt.getTime())[0]!;
    const review = ctx.store.insertReview({
      claimId: claim.id, compositionId: previous?.compositionId ?? null, state: 'pending',
      rule: decision.rule, reason: decision.reason, createdAt: now,
      expiresAt: new Date(now.getTime() + REVIEW_TTL_MINUTES * 60000), resolvedAt: null,
      note: 'Regenerated by owner for manual event-week review; source timestamp is unchanged.',
    });
    reviewIds.push(review.id);
    try {
      const comp = await prepareReview(ctx, review.id);
      if (previous?.compositionId && comp.imagePaths.length === 1) await renderPostDesign(ctx, comp.id, comp.doc ?? null);
    }
    catch (e) { errors.push({ claimId: claim.id, error: (e as Error).message }); }
  }
  ctx.store.log({ stage: 'review', level: 'info', msg: 'regenerated recent F1 manual reviews',
    dedupeHash: null, latencyMs: null, meta: { count: reviewIds.length, reviewIds, errors } });
  return { regenerated: reviewIds.length, reviewIds, errors };
}
